quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:10000}

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
stealth.detect.script=/app/script/detect_public.py

